export const LOGOUT_FAILED = "LOGOUT_FAILED"
export const AUTHENTICATED_FAILED = 'AUTHENTICATED_FAILED';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAILED = 'USER_LOADED_FAILED';